
CREATE TABLE "user" (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	surname VARCHAR(255) NOT NULL, 
	age INTEGER NOT NULL, 
	address VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	PRIMARY KEY (id)
)

